CosineAnnealingLR:
  params:
    T_max: 10
    eta_min: 1e-5
    last_epoch: -1

CosineAnnealingWarmRestarts:
  params:
    T_0: 10
    T_mult: 1
    eta_min: 1e-6
    last_epoch: -1

cosine_schedule_with_warmup:
  params:
    max_epochs: 10
    num_warmup_steps_factor: 10
    # num_training_steps:  max_epochs * len_train_loader

GradualWarmupSchedulerV2:
  params:
    total_epoch: 10
    warmup_epoch: 2
    warmup_factor: 10
    eta_min: 1e-5

ReduceLROnPlateau:
  params:
    mode: min
    factor: 0.75
    patience: 10
    threshold: 1e-4
    threshold_mode: rel
    cooldown: 0
    min_lr: 1e-5
    eps: 1e-8
