model: swinv2_base_window12to24_192to384_22kft1k
batch_size: 8
image_size: 384
seed: 42
pretrained: true
num_workers: 2
pin_memory: true
train_dir: ../input/rice-zindi-comp/
train_file_path: ../input/train-zindi/train.csv
epochs: 25
in_channels: 3
folds:
  - 0
  - 1
  - 2
  - 3
  - 4

scheduler_name: CosineAnnealingWarmRestarts
optimizer: Adam
T_0: 5
T_max: 5
T_mult: 1
min_lr: 1e-7
max_lr: 1e-3
weight_decay: 1e-6
target_size: 3
device: cuda
model_dir: swin_v2_cutout_mixup
n_fold: 5
mixup: True
mixup_alpha: 1.0
pseudo_file_path: ./RiceClassification/submission/swinv2_base_window12to24_192to384_22kft1k_tta.csv
optimizer_args:
  lr: 1.0E-5