defaults:
  - callbacks: callbacks
  - scheduler: cosinewarm
  - optimizer: adamw
  - data_mode: good_quality

general:
  base_dir: ./
  logs_dir: lightning_logs/
  seed: 13
  num_workers: 4
  gpu_list: [0, 1]

model:
  model_id: 1
  regression: false
  architecture_name: resnet50
  dropout: 0.3
  input_size: [256, 256]
  crop_method: resize

training:
  batch_size: 32
  lr: 1e-5
  augmentations: base
  mixup: 0.
  cutmix: 0.
  label_augmentation: 0.
  max_epochs: 20
  fold: 0
  val_metric: val_rmse
  metric_mode: min
  pretrain_dir: ""

testing:
  folds: [0, 1, 2, 3, 4]
  test_csv: data/SampleSubmission.csv
  mode: test
  tta: true

ensemble:
  model_ids: [2, 3, 4, 5, 6]
  postprocessing: false

hydra:
  run:
    dir: ${general.base_dir}
  sweep:
    dir: ${general.base_dir}
    subdir: ""
