aug:
  crop_l: 0.75
  crop_r: 1.3333333333333333
  crop_scale: 0.9
  p_affine: 0.5
  p_blur: 0.05
  p_bright_contrast: 0.5
  p_cutout: 0.05
  p_downscale: 0.0
  p_clahe: 0
  p_rgb_shift: 0
  p_gray: 0.1
  p_noise: 0.05
  p_posterize: 0.2
  p_rain: 0.05
  p_shuffle: 0.3
  p_snow: 0.1
  rotate: 15
  shear: 3
  translate: 0.25
backbone: convnext_large_384_in22ft1k
batch_size: 8
global_pool:
  arch: GeM
  p: 3
  train: false
gradient_accumulation_steps: 4
image_size:
- 384
- 384
img_dir: Images
img_format: rgb
loss: ce
lr_backbone: 0.0001
lr_decay_scale: 0.01
lr_head: 0.0001
max_epochs: 20
mixup: null
model_name: null
model_type: simple
n_data: -1
n_splits: 5
normalization: batchnorm
num_classes: 3
optimizer: AdamW
out_indices:
- 3
- 4
pretrained: true
pretrained_weights: null
pseudo_conf_threshold: null
pseudo_label: null
scheduler:
  method: plateau
seed: 7
train_csv: train_rgb_purged.csv
warmup_steps_ratio: 0.2
weight_decay: 1.0e-05
