seed: 7
model_type: simple
train_csv: train_rgb_purged.csv
img_dir: Images
loss: ce
lr_backbone: 1.6e-3
lr_head: 1.6e-2
lr_decay_scale: 1.0e-2
weight_decay: 1.0e-5
batch_size: 8
image_size:
- 224
- 224
max_epochs: 30
model_name:
out_indices:
- 3
- 4
n_splits: 5
num_classes: 3
pretrained: true
pretrained_weights:
warmup_steps_ratio: 0.2
img_format: rgb
grad_checkpointing: false
n_data: -1
global_pool:
  arch: GeM
  p: 3
  train: false
normalization: batchnorm
optimizer: AdamW
gradient_accumulation_steps: 1
pseudo_label:
pseudo_conf_threshold: 0.0
scheduler: 
  method: cosine
mixup: 
aug:
  rotate: 15
  translate: 0.25
  shear: 3
  p_affine: 0.5
  crop_scale: 0.9
  crop_l: 0.75
  crop_r: 1.3333333333333333
  p_gray: 0.1
  p_blur: 0.05
  p_noise: 0.05
  p_downscale: 0.0
  p_shuffle: 0.3
  p_posterize: 0.2
  p_clahe: 0
  p_rgb_shift: 0
  p_bright_contrast: 0.5
  p_cutout: 0.05
  p_snow: 0.1
  p_rain: 0.05
