aug:
  crop_l: 1.0
  crop_r: 1.0
  crop_scale: 0.9
  p_affine: 0.5
  p_blur: 0.2
  p_bright_contrast: 0.5
  p_cutout: 0.4
  p_downscale: 0.0
  p_gray: 0.1
  p_noise: 0.05
  p_clahe: 0
  p_rgb_shift: 0
  p_posterize: 0.3
  p_rain: 0.05
  p_shuffle: 0.3
  p_snow: 0.1
  rotate: 15
  shear: 3
  translate: 0.25
backbone: swinv2_large_window12_192_22k
batch_size: 32
global_pool:
  arch: GeM
  p: 3
  train: false
grad_checkpointing: true
gradient_accumulation_steps: 1
image_size:
- 192
- 192
img_dir: Images
img_format: rgb
loss: ce
lr_backbone: 2.0e-05
lr_decay_scale: 0.01
lr_head: 2.0e-05
max_epochs: 30
mixup: null
model_name: null
model_type: simple
n_data: -1
n_splits: 5
normalization: batchnorm
num_classes: 3
optimizer: AdamW
out_indices:
- 3
- 4
pretrained: true
pretrained_weights: null
pseudo_conf_threshold: null
pseudo_label: null
scheduler:
  method: cosine
seed: 7
train_csv: train_rgb_purged.csv
warmup_steps_ratio: 0.2
weight_decay: 1.0e-05
