batch_size: 32
lr_backbone: 5.0e-05
lr_head: 5.0e-05
image_size:
- 224
- 224
max_epochs: 30
gradient_accumulation_steps: 1
backbone: vit_base_patch32_224_in21k
out_indices:
- 3
- 4
n_splits: 5
pseudo_label: null
pseudo_conf_threshold: null
seed: 7
model_type: simple
train_csv: train_rgb_purged.csv
img_dir: Images
loss: ce
lr_decay_scale: 0.01
weight_decay: 1.0e-05
model_name: null
num_classes: 3
pretrained: true
pretrained_weights: null
warmup_steps_ratio: 0.2
img_format: rgb
n_data: -1
global_pool:
  arch: GeM
  p: 3
  train: false
normalization: batchnorm
optimizer: AdamW
scheduler:
  method: cosine
aug:
  rotate: 15
  translate: 0.25
  shear: 3
  p_affine: 0.5
  crop_scale: 0.9
  p_clahe: 0
  p_rgb_shift: 0
  crop_l: 0.75
  crop_r: 1.3333333333333333
  p_gray: 0.1
  p_blur: 0.05
  p_noise: 0.05
  p_downscale: 0.0
  p_shuffle: 0.3
  p_posterize: 0.2
  p_bright_contrast: 0.5
  p_cutout: 0.05
  p_snow: 0.1
  p_rain: 0.05
