# @package _group_
early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: ${training.val_metric}
  patience: 50
  mode: ${training.metric_mode}
  verbose: true

model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: ${training.val_metric}
  save_top_k: 1
  filepath: ${general.logs_dir}model_${model.model_id}/fold_${training.fold}/{epoch}-{val_rmse:.3f}
  verbose: true
  save_weights_only: true
  mode: ${training.metric_mode}
  period: 1
  save_last: false

tensorboard:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${general.logs_dir}
  name: model_${model.model_id}
  version: fold_${training.fold}

lr_logger:
  _target_: pytorch_lightning.callbacks.LearningRateLogger
  logging_interval: epoch
