root_dir: "./dataset"
train_dir: "./dataset/TreeImages"
test_dir: "./dataset/TreeImages"
seed: 0
backbone: tf_efficientnetv2_l_in21k
train_batch_size: 16
valid_batch_size: 16
img_size: 512
epochs: 16
learning_rate: 0.0001
scheduler: CosineAnnealingLR
min_lr: 0.000001
T_max: 3
weight_decay: 0.000001
n_accumulate: 1
n_fold: 5
num_classes: 1
log_dir: ./logs
checkpoint_dir: ./checkpoints/tf_efficientnetv2_l_in21k
device: cuda